name = "reset-edu-kakao-auth"
main = "worker.js"
compatibility_date = "2026-03-22"
workers_dev = true

[vars]
APP_BASE_URL = "https://resetedu.kr"
APP_EXTRA_ORIGINS = "https://www.resetedu.kr,https://zzang1.pages.dev"
# KAKAO_REDIRECT_URI should match your deployed Worker URL.
# Example: https://reset-edu-kakao-auth.your-subdomain.workers.dev/api/auth/kakao/callback
KAKAO_REDIRECT_URI = "https://reset-edu-kakao-auth.cfv47.workers.dev/api/auth/kakao/callback"

SUPABASE_URL = "https://ghufoabtkjbizszdzies.supabase.co"
SUPABASE_PROFILE_TABLE = "member_profiles"

FIREBASE_PROJECT_ID = "jaeseung-try-2-34973152-e44aa"
FIREBASE_WEB_API_KEY = "AIzaSyDU9TRAY_Vh7wSN4f5F1ZIzw6xNyX-SbYQ"
PAYMENT_PROVIDER = "portone-kcp-v2"
PORTONE_STORE_ID = "store-09b1afcd-36f9-40cc-8145-0a32d0cabe22"
PORTONE_EXPECTED_CHANNEL_TYPE = "LIVE"
STREAM_UID_SEXUAL_OFFENSE_PREVENTION = "24dacf28f739c167a8f0d3deab08698d"
STREAM_UID_VIOLENCE_PREVENTION = "728ec0f2f08d6e1cf4f6a053f71afc99"
STREAM_UID_GAMBLING_RELAPSE_PREVENTION = "8dbeefe268516e0d6d84c84e35713140"
STREAM_UID_DRUG_ADDICTION_RELAPSE_PREVENTION = "9e7a8bca74cc08b48622a4dcf8df070f"
