name = "zzang1"
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_AUTH_API_BASE_URL = "https://reset-edu-kakao-auth.cfv47.workers.dev"
NEXT_PUBLIC_APP_ORIGIN = "https://resetedu.kr"
NEXT_PUBLIC_SITE_URL = "https://resetedu.kr"
NEXT_PUBLIC_PAYMENT_PROVIDER = "portone-kcp-v2"
NEXT_PUBLIC_PAYMENT_CONFIRM_URL = "https://reset-edu-kakao-auth.cfv47.workers.dev/api/payments/confirm"
NEXT_PUBLIC_PORTONE_STORE_ID = "store-09b1afcd-36f9-40cc-8145-0a32d0cabe22"
NEXT_PUBLIC_PORTONE_KCP_CHANNEL_KEY = "channel-key-240a0839-4bb4-47d7-b642-8598df270d11"
NEXT_PUBLIC_PORTONE_KAKAOPAY_CHANNEL_KEY = "channel-key-a7a3c4a6-57d4-459d-a91e-ab7c96661ec2"
NEXT_PUBLIC_PORTONE_KAKAOPAY_MID = "CA34219176"
NEXT_PUBLIC_STREAM_UID_SEXUAL_OFFENSE_PREVENTION = "24dacf28f739c167a8f0d3deab08698d"
NEXT_PUBLIC_STREAM_UID_VIOLENCE_PREVENTION = "728ec0f2f08d6e1cf4f6a053f71afc99"
NEXT_PUBLIC_STREAM_UID_GAMBLING_RELAPSE_PREVENTION = "8dbeefe268516e0d6d84c84e35713140"
NEXT_PUBLIC_STREAM_UID_DRUG_ADDICTION_RELAPSE_PREVENTION = "9e7a8bca74cc08b48622a4dcf8df070f"
NEXT_PUBLIC_STREAM_UID_DIGITAL_CRIME_PREVENTION = "6ace367027be3fe294639343739e9af5"
NEXT_PUBLIC_STREAM_UID_FRAUD_PREVENTION = "c3ee448bc45d30d329b76a89e2d1a547"
NEXT_PUBLIC_STREAM_UID_UNLICENSED_DRIVING_PREVENTION = "f581475c91de7f8574391ec5daebc008"
NEXT_PUBLIC_STREAM_UID_HANGOVER_DRIVING_PREVENTION = "0a451904c6baea91ab32155f1df3e748"

NEXT_PUBLIC_STREAM_UID_RECKLESS_RETALIATORY_DRIVING_PREVENTION = "d9d7d67167f1874a7b93a964746fb1a8"
NEXT_PUBLIC_STREAM_UID_DEFAMATION_INSULT_PREVENTION = "23341942e913deae11baabedcd24d95b"
NEXT_PUBLIC_STREAM_UID_LEGAL_COMPLIANCE_AWARENESS = "a2b66d1b575d82d361f7680ec1e7e48b"
NEXT_PUBLIC_STREAM_UID_VOICE_PHISHING_PREVENTION = "40db2b4735841194439c22e90d9665be"
NEXT_PUBLIC_STREAM_UID_DIGITAL_SEXUAL_CRIME_PREVENTION = "fa6e84899afa4f5f1314b6c145c27feb"
NEXT_PUBLIC_STREAM_UID_PROSTITUTION_PREVENTION = "d01b607c43e0c6232706656082d044b8"
