name = "reset-edu-kakao-auth"
main = "worker.js"
compatibility_date = "2026-03-22"
workers_dev = true

[vars]
APP_BASE_URL = "https://resetedu.kr"
APP_EXTRA_ORIGINS = "https://www.resetedu.kr,https://zzang1.pages.dev"
# KAKAO_REDIRECT_URI should match your deployed Worker URL.
# Example: https://reset-edu-kakao-auth.your-subdomain.workers.dev/api/auth/kakao/callback
KAKAO_REDIRECT_URI = "https://reset-edu-kakao-auth.cfv47.workers.dev/api/auth/kakao/callback"

SUPABASE_URL = "https://ghufoabtkjbizszdzies.supabase.co"
SUPABASE_PROFILE_TABLE = "member_profiles"

FIREBASE_PROJECT_ID = "jaeseung-try-2-34973152-e44aa"
FIREBASE_WEB_API_KEY = "AIzaSyDU9TRAY_Vh7wSN4f5F1ZIzw6xNyX-SbYQ"
PAYMENT_PROVIDER = "portone-kcp-v2"
PORTONE_STORE_ID = "store-09b1afcd-36f9-40cc-8145-0a32d0cabe22"
PORTONE_EXPECTED_CHANNEL_TYPE = "LIVE"
STREAM_UID_SEXUAL_OFFENSE_PREVENTION = "24dacf28f739c167a8f0d3deab08698d"
STREAM_UID_VIOLENCE_PREVENTION = "728ec0f2f08d6e1cf4f6a053f71afc99"
STREAM_UID_GAMBLING_RELAPSE_PREVENTION = "8dbeefe268516e0d6d84c84e35713140"
STREAM_UID_DRUG_ADDICTION_RELAPSE_PREVENTION = "9e7a8bca74cc08b48622a4dcf8df070f"
STREAM_UID_DIGITAL_CRIME_PREVENTION = "6ace367027be3fe294639343739e9af5"
STREAM_UID_FRAUD_PREVENTION = "c3ee448bc45d30d329b76a89e2d1a547"
STREAM_UID_UNLICENSED_DRIVING_PREVENTION = "f581475c91de7f8574391ec5daebc008"
STREAM_UID_HANGOVER_DRIVING_PREVENTION = "0a451904c6baea91ab32155f1df3e748"
STREAM_UID_RECKLESS_RETALIATORY_DRIVING_PREVENTION = "d9d7d67167f1874a7b93a964746fb1a8"
STREAM_UID_DEFAMATION_INSULT_PREVENTION = "23341942e913deae11baabedcd24d95b"

STREAM_UID_LEGAL_COMPLIANCE_AWARENESS = "a2b66d1b575d82d361f7680ec1e7e48b"
STREAM_UID_VOICE_PHISHING_PREVENTION = "40db2b4735841194439c22e90d9665be"
STREAM_UID_DIGITAL_SEXUAL_CRIME_PREVENTION = "fa6e84899afa4f5f1314b6c145c27feb"
STREAM_UID_PROSTITUTION_PREVENTION = "d01b607c43e0c6232706656082d044b8"
